// Code generated by "stringer -type=MQTTControlPacketType"; DO NOT EDIT.

package mqtt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RESERVED_PACKET_TYPE-0]
	_ = x[CONNECT-1]
	_ = x[CONNACK-2]
	_ = x[PUBLISH-3]
	_ = x[PUBACK-4]
	_ = x[PUBREC-5]
	_ = x[PUBREL-6]
	_ = x[PUBCOMP-7]
	_ = x[SUBSCRIBE-8]
	_ = x[SUBACK-9]
	_ = x[UNSUBSCRIBE-10]
	_ = x[UNSUBACK-11]
	_ = x[PINGREQ-12]
	_ = x[PINGRESP-13]
	_ = x[DISCONNECT-14]
	_ = x[RESERVED_PACKET_TYPE_2-15]
}

const _MQTTControlPacketType_name = "RESERVED_PACKET_TYPECONNECTCONNACKPUBLISHPUBACKPUBRECPUBRELPUBCOMPSUBSCRIBESUBACKUNSUBSCRIBEUNSUBACKPINGREQPINGRESPDISCONNECTRESERVED_PACKET_TYPE_2"

var _MQTTControlPacketType_index = [...]uint8{0, 20, 27, 34, 41, 47, 53, 59, 66, 75, 81, 92, 100, 107, 115, 125, 147}

func (i MQTTControlPacketType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MQTTControlPacketType_index)-1 {
		return "MQTTControlPacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MQTTControlPacketType_name[_MQTTControlPacketType_index[idx]:_MQTTControlPacketType_index[idx+1]]
}
