// Code generated by "stringer -type=MQTTControlPacketType"; DO NOT EDIT.

package mqtt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RESERVED_PACKET_TYPE-0]
	_ = x[CONNECT-1]
	_ = x[CONNACK-2]
	_ = x[PUBACK-3]
	_ = x[PUBREC-4]
	_ = x[PUBREL-5]
	_ = x[PUBCOMP-6]
	_ = x[SUBSCRIBE-7]
	_ = x[SUBACK-8]
	_ = x[UNSUBSCRIBE-9]
	_ = x[UNSUBACK-10]
	_ = x[PINGREQ-11]
	_ = x[PINGRESP-12]
	_ = x[DISCONNECT-13]
}

const _MQTTControlPacketType_name = "RESERVED_PACKET_TYPECONNECTCONNACKPUBACKPUBRECPUBRELPUBCOMPSUBSCRIBESUBACKUNSUBSCRIBEUNSUBACKPINGREQPINGRESPDISCONNECT"

var _MQTTControlPacketType_index = [...]uint8{0, 20, 27, 34, 40, 46, 52, 59, 68, 74, 85, 93, 100, 108, 118}

func (i MQTTControlPacketType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MQTTControlPacketType_index)-1 {
		return "MQTTControlPacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MQTTControlPacketType_name[_MQTTControlPacketType_index[idx]:_MQTTControlPacketType_index[idx+1]]
}
